name: CI

on:
  pull_request:
    branches:
      - master

jobs:

  lint-imports:
    name: Lint Python Imports
    runs-on: ubuntu-20.04

    steps:
    - name: Check out branch
      uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system packages
      run: |
        sudo apt-get update && sudo apt-get install libxmlsec1-dev

    - name: Install Python dependencies
      if: steps.cache-dependencies.output.cache-hit != 'true'
      run: |
        pip install setuptools wheel
        pip install -r requirements/edx/testing.txt

    - name: Analyze imports within root packages
      run: make lint-imports-root

    - name: Analyze imports within common/lib
      run: make lint-imports-common-lib
